import streamlit as st
import sys
import os
from datetime import date, timedelta

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from models.student import StudentInput
from agents.orchestrator import OrchestratorAgent
from foundry.client import FoundryIQClient
from i18n import get_language_manager, Language, t

_lang_map = {
    "English": "en",
    "हिंदी (Hindi)": "hi",
    "தமிழ் (Tamil)": "ta",
    "ಕನ್ನಡ (Kannada)": "kn",
}
_selected_lang = st.session_state.get("language_selector", "English")
try:
    _lm = get_language_manager()
    _lang_code = _lang_map.get(_selected_lang, "en")
    _lang_enum_map = {"en": Language.ENGLISH, "hi": Language.HINDI, "ta": Language.TAMIL, "kn": Language.KANNADA}
    _lm.set_language(_lang_enum_map.get(_lang_code, Language.ENGLISH))
    def _t(key, default=""):
        res = _lm.translate(key)
        if res == key and default:
            return default
        return res
except Exception:
    _t = lambda key, default="": default or key

DEGREE_CATALOG = {
    "TECH": {
        "BTech / BE": ["Artificial Intelligence", "Data Science", "Cybersecurity", "Software Engineering"],
        "BCA": ["Software Development", "Data Analytics", "Cloud Computing"],
        "BSc Computer Science": ["Artificial Intelligence", "Data Science", "Systems"],
    },
    "BUSINESS": {
        "BBA": ["Marketing", "Finance", "HR"],
        "BCom": ["Accounting", "Finance", "Taxation"],
        "Economics": ["Econometrics", "Policy", "Finance"],
    },
    "LAW": {"LLB": ["Corporate Law", "Criminal Law", "IP Law"], "BA LLB": ["Policy", "Human Rights"]},
    "CREATIVE": {"Design": ["UX Design", "Product Design"], "Architecture": ["Sustainable Architecture"]},
    "MEDICAL": {"MBBS": ["General Medicine", "Public Health"], "BDS": ["Dental Surgery"]},
}


def status_label(level: str) -> str:
    colors = {
        "weak": "red",
        "moderate": "yellow",
        "strong": "green",
        "high": "red",
        "low": "green",
    }
    color = colors.get(level, "yellow")
    return f":{color}[{level.upper()}]"


def clear_report():
    st.session_state.report = None
    st.session_state.student = None
    st.session_state.analyzed = False

def extract_ai_content(ai_resp) -> str:
    if isinstance(ai_resp, dict):
        return ai_resp.get("content", str(ai_resp))
    elif isinstance(ai_resp, str) and ai_resp.strip().startswith("{"):
        import json
        try:
            return json.loads(ai_resp).get("content", ai_resp)
        except Exception:
            return ai_resp
    return str(ai_resp) if ai_resp else ""


def render_practice_tab(report):
    st.markdown("### 📝 Readiness Assessment")
    st.caption("Generated by Assessment Agent")
    assessment = getattr(report, "assessment", None) or {}
    if not assessment:
        st.info("Assessment is being generated. Run the analysis first.")
        return

    final_output = assessment.get("final_output", "")
    st.write(final_output)


def render_reasoning_tab(report, wa, ra, ev):
    st.markdown("### 🧠 Multi-Agent Grounding & Evidence")
    
    agent_outputs = {
        "Learning Path Curator": getattr(report, "learning_path", {}),
        "Study Planner": getattr(report, "study_plan", {}),
        "Engagement Agent": getattr(report, "engagement_tracking", {}),
        "Assessment Agent": getattr(report, "assessment", {}),
        "Manager Insights Agent": getattr(report, "manager_insights", {}),
        "Weakness Analyzer": getattr(report, "weakness_analysis", {}),
        "Risk Predictor": getattr(report, "risk_assessment", {}),
        "Resource Finder": getattr(report, "resources", {}),
        "Career Readiness": getattr(report, "career_readiness", {}),
        "Counterfactual Reasoner": getattr(report, "counterfactuals", {}),
    }

    for agent_name, payload in agent_outputs.items():
        if not payload:
            continue
        trace = payload.get("reasoning_trace", [])
        evidence = payload.get("evidence", [])
        confidence = payload.get("confidence", 0) * 100
        
        with st.expander(f"⚙️ {agent_name} — Confidence: {confidence:.0f}%"):
            st.markdown("**Reasoning Trace:**")
            if trace:
                for step in (trace if isinstance(trace, list) else [trace]):
                    st.write(f"→ {step}")
            else:
                st.caption("No trace available")
                
            st.markdown("**Grounded Evidence:**")
            if evidence:
                for e in (evidence if isinstance(evidence, list) else [evidence]):
                    st.write(f"• {e}")
            else:
                st.caption("No evidence provided (Warning: Potential Hallucination)")

            if payload.get("why_this_decision"):
                st.caption(f"*Decision Logic:* {payload.get('why_this_decision')}")
    st.markdown("### 🤝 Multi-agent consensus")
    consensus = report.consensus or {}
    if consensus:
        c1, c2, c3 = st.columns(3)
        c1.metric("Agents engaged", consensus.get("agents_engaged", 0))
        c2.metric("Overall confidence", f"{consensus.get('overall_confidence', 0):.1f}%")
        c3.metric("Conflicts found", len(consensus.get("conflicts", consensus.get("disagreement_areas", []))))
        for area in consensus.get("consensus_areas", []):
            with st.expander(f"📊 {area.get('topic', 'Consensus area')}"):
                st.write(f"**Result:** {area.get('consensus', '')}")
                st.write(f"**Resolution:** {area.get('resolution', '')}")
                opinions = area.get("opinions", area.get("agent_opinions", []))
                for op in opinions:
                    conf = op.get("confidence", 0)
                    bar = "█" * int(conf / 10) + "░" * (10 - int(conf / 10))
                    st.write(f"• **{op.get('agent', 'Agent')}** [{bar}] {conf:.0f}%: {op.get('opinion', '')}")
    else:
        st.info("Run analysis to see agent consensus")

    st.markdown("### 🧐 Critic agent review")
    critic = report.critic_review or {}
    flaws = critic.get("flaws", [])
    improvements = critic.get("suggested_improvements", critic.get("improvements", []))
    if flaws:
        for flaw in flaws:
            st.warning(f"⚠️ {flaw}")
    else:
        st.success("✅ No critical flaws detected")
    if improvements:
        st.markdown("**Suggested improvements:**")
        for imp in improvements:
            st.write(f"• {imp}")

    st.markdown("### ⚡ Observability & latency")
    chain = ev.get("agent_execution_chain", report.observability.get("agent_execution_chain", []) if report.observability else [])
    if chain:
        total_ms = sum(step.get("latency_ms", 0) for step in chain)
        st.metric("Total pipeline latency", f"{total_ms:.2f}ms")
        col1, col2 = st.columns(2)
        for i, step in enumerate(chain):
            with (col1 if i % 2 == 0 else col2):
                st.metric(step.get("agent", "Agent"), f"{step.get('latency_ms', 0):.2f}ms")
    else:
        st.info("No observability data — run analysis first")

    st.markdown("### 📊 System self-evaluation")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Reasoning", f"{ev.get('reasoning_quality_score', 0):.1f}%")
    c2.metric("Consistency", f"{ev.get('consistency_score', 0):.1f}%")
    c3.metric("Reliability", f"{ev.get('reliability_score', 0):.1f}%")
    c4.metric("Explainability", f"{ev.get('explainability_score', 0):.1f}%")
    for suggestion in ev.get("improvement_suggestions", []):
        st.caption(f"• {suggestion}")
    for d in ev.get("deductions", []):
        st.caption(f"• {d[0]}: {d[1]} points")


st.set_page_config(page_title="StudyMate AI", page_icon="🎓", layout="wide")

_fiq_status = FoundryIQClient()
if _fiq_status.is_live():
    st.success(
        f"⚡ **Foundry IQ: LIVE** — {_fiq_status.get_source_label()} active | "
        f"All recommendations are grounded and cited"
    )
else:
    st.info(
        "🔵 **Foundry IQ: Synthetic mode** — "
        "Add FOUNDRY_API_KEY or AZURE_OPENAI_KEY to .env for live Microsoft Foundry IQ retrieval"
    )

_LANG_OPTIONS = {
    "English": "en",
    "हिंदी (Hindi)": "hi",
    "தமிழ் (Tamil)": "ta",
    "ಕನ್ನಡ (Kannada)": "kn",
}

for key, default in [
    ("report", None),
    ("student", None),
    ("analyzed", False),
    ("level_confirmed", False),
    ("profile_confirmed", False),
    ("form_nonce", 0),
    ("last_level", "school"),
    ("last_subject_count", 3),
    ("lang_code", "en"),
]:
    if key not in st.session_state:
        st.session_state[key] = default

with st.sidebar:
    st.title(f"🎓 {t('app_title')}")
    st.caption(t("privacy_caption"))
    st.markdown("### Flow")
    st.markdown("1. Select & confirm level\n2. Confirm profile\n3. Run analysis")
    st.divider()
    for agent in [
        "Orchestrator", "Weakness Analyzer", "Study Planner",
        "Risk Predictor", "Resource Finder", "Career Readiness",
        "Consensus", "Critic", "Counterfactual", "Evaluator", "Mock Exam",
    ]:
        st.markdown(f"• {agent}")
    st.divider()
    st.markdown("### 🌐 Language / भाषा")
    _lang_choice = st.selectbox(
        "Select language",
        list(_LANG_OPTIONS.keys()),
        key="language_selector",
        label_visibility="collapsed",
    )
    try:
        from i18n import get_language_manager, Language
        _lm = get_language_manager()
        _lang_code_sb = _lang_map.get(_lang_choice, "en")
        _lang_enum_map_sb = {"en": Language.ENGLISH, "hi": Language.HINDI, "ta": Language.TAMIL, "kn": Language.KANNADA}
        _lm.set_language(_lang_enum_map_sb.get(_lang_code_sb, Language.ENGLISH))
        _orig_translate = _lm.translate
        def _wrapped_translate(key, default=""):
            res = _orig_translate(key)
            if res == key and default:
                return default
            return res
        _t = _wrapped_translate
    except Exception:
        _t = lambda key, default="": default or key
    st.divider()
    st.markdown("### 🔗 Foundry IQ")
    if _fiq_status.is_live():
        st.success(f"✅ {_fiq_status.get_source_label()}")
        st.caption("Live grounded knowledge retrieval active")
    else:
        st.warning("⚠️ Synthetic mode")
        st.caption("Add API key to .env for live retrieval")
    st.divider()
    st.caption("🏆 Agents League Hackathon 2026")
    st.caption("Track: Reasoning Agents")
    st.caption("Built by Saksham Dixit | PSIT Kanpur")
    st.caption("github.com/sakshamd19/studymate-ai")

st.markdown(
    f"# {_t('app_title', '🎓 StudyMate AI')}"
)
st.markdown(
    f"##### {_t('app_subtitle', 'Tell us about your studies — 6 AI agents will build your personalised plan')}"
)
st.divider()

learner_level = st.selectbox(
    "Step 1 — Learner level",
    ["school", "CBSE", "university", "advanced"],
    key="learner_level_select",
)
if learner_level != st.session_state.last_level:
    st.session_state.last_level = learner_level
    st.session_state.level_confirmed = False
    st.session_state.profile_confirmed = False
    clear_report()
    st.session_state.form_nonce += 1

if st.button("Confirm level", key="confirm_level"):
    st.session_state.level_confirmed = True
    st.session_state.profile_confirmed = False
    clear_report()

if not st.session_state.level_confirmed:
    st.info("Confirm learner level to unlock degree/stream and subject fields.")
    st.stop()

stream = ""
degree_group = ""
degree = ""
specialization = ""
nonce = st.session_state.form_nonce

with st.form("student_form"):
    student_name = st.text_input("Your name", placeholder="e.g. Saksham Dixit")
    interest = st.text_input("Interest (optional)", placeholder="e.g. AI, finance, design")

    if learner_level.lower() in {"school", "cbse"}:
        stream = st.selectbox("School stream", ["Science", "Commerce", "Humanities"], key=f"stream_{nonce}")
    else:
        degree_group = st.selectbox("Degree group", list(DEGREE_CATALOG.keys()), key=f"group_{nonce}")
        degree = st.selectbox("Degree", list(DEGREE_CATALOG[degree_group].keys()), key=f"degree_{nonce}")
        specialization = st.selectbox(
            "Specialization",
            DEGREE_CATALOG[degree_group][degree],
            key=f"spec_{nonce}",
        )
        stream = degree_group

    num_subjects = st.number_input("Number of subjects", min_value=1, max_value=8, value=3, key=f"num_{nonce}")
    if int(num_subjects) != st.session_state.last_subject_count:
        st.session_state.last_subject_count = int(num_subjects)
        clear_report()

    st.markdown("### Subjects")
    subject_data = []
    for i in range(int(num_subjects)):
        col1, col2, col3, col4 = st.columns([3, 2, 2, 3])
        with col1:
            sub_name = st.text_input(f"Subject {i+1}", key=f"sub_{nonce}_{i}", placeholder="Mathematics")
        with col2:
            score = st.number_input("Score", key=f"score_{nonce}_{i}", min_value=0.0, max_value=100.0, value=50.0)
        with col3:
            confidence = st.slider("Confidence", 0.1, 1.0, 0.75, 0.05, key=f"conf_{nonce}_{i}")
        with col4:
            exam_date = st.date_input("Exam date", key=f"date_{nonce}_{i}", value=date.today() + timedelta(days=14))
        subject_data.append((sub_name, score, exam_date, confidence))

    c1, c2, c3 = st.columns(3)
    with c1:
        profile_submit = st.form_submit_button("Confirm profile", use_container_width=True)
    with c2:
        submitted = st.form_submit_button(
            _t('analyze_button', '🔍 Analyze My Studies'),
            use_container_width=True
        )
        analyze_submit = submitted
    with c3:
        reset = st.form_submit_button("Reset", use_container_width=True)

if reset:
    clear_report()
    st.session_state.level_confirmed = False
    st.session_state.profile_confirmed = False
    st.session_state.form_nonce += 1
    st.rerun()

if profile_submit:
    if not student_name.strip():
        st.error("Enter your name.")
    elif not any(s[0].strip() for s in subject_data):
        st.error("Add at least one subject.")
    else:
        st.session_state.profile_confirmed = True
        clear_report()
        st.success("Profile confirmed. Click **Run analysis** when ready.")

if analyze_submit:
    if not st.session_state.profile_confirmed:
        st.warning("Confirm profile before running analysis.")
    elif not student_name.strip():
        st.error("Enter your name.")
    else:
        student = StudentInput(
            name=student_name.strip(),
            stream=stream or "General",
            learner_level=learner_level.lower(),
            degree_group=degree_group,
            degree=degree,
            specialization=specialization,
            interest=interest,
        )
        for sub_name, score, exam_date, confidence in subject_data:
            if sub_name.strip():
                student.add_subject(sub_name.strip(), score, exam_date, confidence=confidence)

        with st.spinner("Running multi-agent analysis via Foundry IQ..."):
            try:
                report = OrchestratorAgent().run(student)
                st.session_state.report = report
                st.session_state.student = student
                st.session_state.analyzed = True
                st.success("Analysis complete.")
            except Exception as exc:
                st.error(f"Analysis failed: {exc}")

if st.session_state.analyzed and st.session_state.report:
    report = st.session_state.report
    student = st.session_state.student
    wa = report.weakness_analysis
    ra = report.risk_assessment
    sp = report.study_plan
    res = report.resources
    cr = report.career_readiness
    ev = report.evaluation or {}

    st.divider()
    st.markdown(f"## 📊 Report — {student.name}")
    weakest = (wa.get("weakest_subject") or {}).get("subject", "—")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Overall average", f"{wa.get('overall_average', 0)}%")
    c2.metric("Weakest subject", weakest)
    c3.metric("Overall risk", f"{ra.get('overall_risk_score', 0)}%")
    c4.metric("Study days", sp.get("plan_duration_days", 0))
    c5.metric("Consistency", f"{(report.consistency or {}).get('consistency_score', 0)}%")

    fiq_grounded_count = sum(
        1 for a in wa.get("all_analyses", [])
        if a.get("foundry_iq_grounded", False)
    )
    total_subjects = len(wa.get("all_analyses", []))
    fiq_src = (
        wa.get("all_analyses", [{}])[0].get("foundry_iq_source", "Synthetic")
        if wa.get("all_analyses") else "Synthetic"
    )
    if fiq_grounded_count > 0:
        st.success(
            f"⚡ **Foundry IQ active** — {fiq_grounded_count}/{total_subjects} "
            f"recommendations grounded via {fiq_src}"
        )
    else:
        st.info(
            "🔵 **Foundry IQ synthetic mode** — "
            "Add GITHUB_TOKEN or GROQ_API_KEY to .env for live grounded recommendations"
        )

    overall_risk = ra.get("overall_risk_score", 50)
    if overall_risk >= 70:
        st.error(
            "🚨 **High alert** — Multiple subjects at critical risk. "
            "Your personalised recovery plan is ready below. Act today."
        )
    elif overall_risk >= 45:
        st.warning(
            "⚠️ **Moderate risk** — Some subjects need attention. "
            "Follow the study plan consistently and you can recover."
        )
    else:
        st.success(
            "✅ **On track** — Your risk profile is manageable. "
            "Stay consistent with the plan to maintain and improve."
        )

    if student.subjects:
        nearest_exam = min(student.subjects, key=lambda s: s.days_until_exam)
        days_left = nearest_exam.days_until_exam
        if 0 < days_left <= 3:
            st.error(f"🔔 **{nearest_exam.name}** exam in **{days_left} day(s)**!")
        elif 3 < days_left <= 7:
            st.warning(f"📅 **{nearest_exam.name}** exam in {days_left} days")

    tabs = st.tabs([
        "🔵 Weakness",
        "📅 Study Plan",
        "⚠️ Risk",
        "📚 Resources",
        "💼 Career",
        "📝 Readiness Assessment",
        "🧠 Agent Intelligence",
    ])

    with tabs[0]:
        st.markdown(f"**{wa.get('summary', '')}**")
        for a in wa.get("all_analyses", []):
            with st.expander(f"{a['subject']} — {a['percentage']}% [{a['weakness_level'].upper()}]"):
                st.progress(int(a["percentage"]))
                st.write(f"Priority score: {a.get('priority_score')} | Confidence: {a.get('confidence')}")
                for s in a.get("suggestions", []):
                    st.write(f"• {s}")
                ai_tip_raw = a.get("ai_suggestions")
                if ai_tip_raw:
                    ai_tip = extract_ai_content(ai_tip_raw)
                    if ai_tip and not ai_tip.startswith("[Synthetic"):
                        st.markdown("**🤖 Foundry IQ recommendation:**")
                        st.info(ai_tip)
                    st.caption(
                        f"Source: {a.get('foundry_iq_source', 'Foundry IQ')}"
                    )

    with tabs[1]:
        st.info(sp.get("tip", ""))
        for day in sp.get("daily_schedule", [])[:14]:
            with st.expander(f"Day {day['day']} — {day['total_hours']} hrs"):
                for sub in day.get("subjects", []):
                    st.markdown(f"**{sub['name']}** — {sub['hours']}h | {status_label(sub['weakness_level'])}")
                    if sub.get("hour_reason"):
                        st.caption(sub["hour_reason"])
                    for focus in sub.get("focus_areas", []):
                        st.write(f"• {focus}")
        ai_strat_raw = sp.get("ai_strategy")
        if ai_strat_raw:
            ai_strat = extract_ai_content(ai_strat_raw)
            if ai_strat and not ai_strat.startswith("[Synthetic"):
                st.divider()
                st.markdown("### 🤖 Foundry IQ strategic overlay")
                st.info(ai_strat)
            st.caption(
                f"Source: {sp.get('foundry_iq_source', 'Foundry IQ')}"
            )

    with tabs[2]:
        if ra.get("urgent_action"):
            st.error(ra.get("overall_verdict"))
        else:
            st.success(ra.get("overall_verdict"))
        for s in ra.get("subject_risks", []):
            with st.expander(f"{s['subject']} — risk {s['risk_score']}%"):
                st.write(s.get("prediction"))
                for step in s.get("recovery_plan", []):
                    st.write(f"• {step}")
                ai_rec_raw = s.get("ai_recovery_plan")
                if ai_rec_raw:
                    ai_rec = extract_ai_content(ai_rec_raw)
                    if ai_rec and not ai_rec.startswith("[Synthetic"):
                        st.markdown("**🤖 Foundry IQ recovery plan:**")
                        st.success(ai_rec)

    with tabs[3]:
        for sr in res.get("subject_resources", []):
            with st.expander(f"{sr['subject']} | {sr.get('weakness_level', '').upper()}"):
                st.caption(sr.get("selection_reason", ""))
                for resource in sr.get("curated_resources", []):
                    st.markdown(f"• [{resource['title']}]({resource['url']}) — {resource['why']}")
                ai_res_raw = sr.get("ai_curated_resources")
                if ai_res_raw:
                    ai_res = extract_ai_content(ai_res_raw)
                    if ai_res and not ai_res.startswith("[Synthetic"):
                        st.divider()
                        st.markdown("**🤖 Foundry IQ curated resources:**")
                        st.info(ai_res)

    with tabs[4]:
        if cr.get("career_recommendation"):
            rec = cr["career_recommendation"]
            st.markdown(f"**{rec.get('career')}** — match {rec.get('match')}")
            st.write(rec.get("why_this_path", ""))
        for path in cr.get("career_paths", [])[:3]:
            st.markdown(f"• **{path['title']}** — {path['avg_salary']}")
        ai_career_raw = cr.get("ai_career_advice")
        if ai_career_raw:
            ai_career = extract_ai_content(ai_career_raw)
            if ai_career and not ai_career.startswith("[Synthetic"):
                st.divider()
                st.markdown("### 🤖 Foundry IQ career intelligence")
                st.info(ai_career)
            st.caption(
                f"Source: {cr.get('foundry_iq_source', 'Foundry IQ')} | "
                f"Grounded: {cr.get('foundry_iq_grounded', False)}"
            )

    with tabs[5]:
        render_practice_tab(report)

    with tabs[6]:
        render_reasoning_tab(report, wa, ra, ev)
